baseURL = "https://sankalp-chudmunge.pages.dev/"
languageCode = "en-us"
title = "Sankalp Chudmunge Blog"
theme = "PaperMod"

[params]
  author = "Sankalp Chudmunge"
  description = "Blog by Sankalp Chudmunge"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  cover.responsiveImages = false
  cover.linkFullImages = false

  [params.label]
    text = "Sankalp Chudmunge"
    icon = "favicon-32x32.png"
    iconHeight = 35

  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
