baseURL = "https://sankalp-chudmunge.pages.dev/"
languageCode = "en-us"
title = "Sankalp Chudmunge Blog"
theme = "PaperMod"
canonifyURLs = true
relativeURLs = true

[params]
  author = "Sankalp Chudmunge"
  description = "Blog by Sankalp Chudmunge"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowViewCount = true
  cover.responsiveImages = false
  cover.linkFullImages = false
  mainSections = ["posts", "projects"]

  [params.label]
    text = "Sankalp Chudmunge"

  [params.assets]

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
