baseURL = "https://sankalp-chudmunge.pages.dev/"
languageCode = "en-us"
title = "Sankalp Chudmunge Blog"
theme = "PaperMod"

[params]
  author = "Sankalp Chudmunge"
  description = "Blog by Sankalp Chudmunge"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  cover.responsiveImages = false
  cover.linkFullImages = false
